### ISSUE TITLE
Windows 10 환경에서 창 이동 시 레이아웃 깨짐 발생합니다.

### ISSUE THREAD

**Issue by che5ya** [joon610/mockup-server#1]
![image](https://user-images.githubusercontent.com/15936615/71395115-e7220c80-2657-11ea-9bb5-8e570b44169b.png)

최초 실행 시에는 정상 표시가 됩니다.

![image](https://user-images.githubusercontent.com/15936615/71395124-f43efb80-2657-11ea-86fa-4bd1e77c1b76.png)

창을 드래그하였을 경우 위와 같이 레이아웃 틀어짐이 발생합니다.

**Comment by che5ya** [comment]
![image](https://user-images.githubusercontent.com/15936615/71395154-13d62400-2658-11ea-8d8f-9f1e57b2372b.png)

위 환경에서 확인했습니다.

**Comment by che5ya** [comment]
윈도우 10 환경에서 스크롤은 항상 표시되는 것을 확인했습니다.
"창 드래그 시 레이아웃이 깨짐"으로 이슈 주제를 변경합니다.

**Comment by joon610** [comment]
오 첫번째 이슈 등록 감사드립니다..  이전 버전에서 생긴 문제입니다. 현재 버전을 확인해주세요..
v0.2.6 버전을 인스톨하면 문제가 해결될거라고 생각됩니다 ^^

**Comment by che5ya** [comment]
예전 페이스북에 올리셨던 링크를 타고 들어가서 다운받았었는데, 최신 릴리즈가 아니었군요!
감사합니다!
