### ISSUE TITLE
[request] Auto Restart Server when json file changed

### ISSUE THREAD

**Issue by mopsyshin** [joon610/mockup-server#6]
목업서버 유용하게 잘 쓰고 있습니다!

쓰다보니 서버 내부 json파일을 수정했을 때 자동으로 server restart되도록 (혹은 옵셔널하게) 하면 좋을 것 같아서 남겨봅니다!

감사합니다 :)

**Comment by joon610** [comment]
오 유용하게 사용해주셔서 감사합니다 아마 가능할꺼 같네요. ㅎ 다음 버전에 추가하도록 하겠습니다

**Comment by joon610** [comment]
업데이트 완료.!
